'use client';

/** slug -> demo component. Split from the catalog so `registry/index.ts` stays
 *  plain data a server component may read. A slug absent here has no standalone
 *  demo (a hook, a script tag) and the page says so. */

import * as D from './index';

export const DEMOS: Record<string, React.ComponentType> = {
  'app-shell': D.AppShellDemo,
  'nav-menu': D.NavMenuDemo,
  'sidebar': D.SidebarDemo,
  'topbar': D.TopbarDemo,
  'breadcrumbs': D.BreadcrumbsDemo,
  'splitter': D.SplitterDemo,
  'tabs': D.TabsDemo,
  'card': D.CardDemo,
  'button': D.ButtonDemo,
  'alert': D.AlertDemo,
  'avatar': D.AvatarDemo,
  'empty-state': D.EmptyStateDemo,
  'menu-icon': D.MenuIconDemo,
  'user-dropdown': D.UserDropdownDemo,
  'theme-settings': D.ThemeSettingsDemo,
  'idle-logout': D.IdleLogoutDemo,
  'field': D.FieldDemo,
  'checkbox': D.CheckboxDemo,
  'toggle-switch': D.ToggleSwitchDemo,
  'multi-select': D.MultiSelectDemo,
  'autocomplete-dropdown': D.AutocompleteDropdownDemo,
  'tree-multi-select-dropdown': D.TreeMultiSelectDropdownDemo,
  'combined-filter-dropdown': D.CombinedFilterDropdownDemo,
  'date-picker': D.DatePickerDemo,
  'date-range-picker': D.DateRangePickerDemo,
  'month-picker': D.MonthPickerDemo,
  'month-range-picker': D.MonthRangePickerDemo,
  'month-grid': D.MonthGridDemo,
  'data-table': D.DataTableDemo,
  'pasteable-grid': D.PasteableGridDemo,
  'editable-cell': D.EditableCellDemo,
  'pagination': D.PaginationDemo,
  'url-pagination': D.UrlPaginationDemo,
  'sortable-th': D.SortableThDemo,
  'sortable-list': D.SortableListDemo,
  'save-all-bar': D.SaveAllBarDemo,
  'account-cell': D.AccountCellDemo,
  'kpi-tile': D.KpiTileDemo,
  'ranked-table': D.RankedTableDemo,
  'ranked-bars': D.RankedBarsDemo,
  'trend-chart': D.TrendChartDemo,
  'retention-chart': D.RetentionChartDemo,
  'activity-feed': D.ActivityFeedDemo,
  'status-bar': D.StatusBarDemo,
  'status-steps': D.StatusStepsDemo,
  'badge': D.BadgeDemo,
  'progress': D.ProgressDemo,
  'skeleton': D.SkeletonDemo,
  'modal': D.ModalDemo,
  'drawer': D.DrawerDemo,
  'tooltip': D.TooltipDemo,
  'confirm-popover': D.ConfirmPopoverDemo,
  'notification-bell': D.NotificationBellDemo,
  'notification-card': D.NotificationCardDemo,
  'media-library': D.MediaLibraryDemo,
};
